modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/CyberDay1/TheExpanse/issues"
license = "MIT"

[[mods]]
    modId="tectonicexpanded"
    version="${mod_version}"
    displayName="Tectonic Expanded"
    description="Expanded tectonic worldgen"
    authors="CyberDay1"
    logoFile="pack.png"

[[dependencies.tectonicexpanded]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.tectonicexpanded]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.21.2)"

