modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/CyberDay1/TheExpanse/issues"
license = "MIT"

[[mods]]
    modId = "theexpanse"
    version = "${mod_version}"
    displayName = "The Expanse"
    description = "Terrain shaping brought to new heights, grander and more varied than ever before. Welcome to The Expanse."
    authors = "Apollo (Developer), HB Stratos (Contributor), DawnKiro (Contributor), Uni (Contributor)"
    logoFile = "pack.png"

[[dependencies.theexpanse]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.5.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.theexpanse]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.5,1.21.6)"

[[dependencies.theexpanse]]
    modId = "lithostitched"
    type = "required"
    ordering = "NONE"
    side = "BOTH"
