modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''Terrain shaping brought to new heights, grander and more varied than ever before. Welcome to Tectonic v3.'''
    authors = "${mod_author}"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true