modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Apollounknowndev/tectonic/issues"
license = "MIT"

[[mods]]
    modId = "tectonic"
    version = "${mod_version}"
    displayName = "Tectonic"
    description = '''Terrain shaping brought to new heights, grander and more varied than ever before. Welcome to Tectonic v3.'''
    authors = "Apollo (Developer), HB Stratos (Contributor), DawnKiro (Contributor), Uni (Contributor)"
    logoFile = "pack.png"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"

[[dependencies.${mod_id}]]
    modId = "lithostitched"
    type = "required"
    ordering = "NONE"
    side = "BOTH"